export const ActionTypes = {
    FETCH_EVENTS: "FETCH_EVENTS",
    POST_EVENT: "POST_EVENT",
    REGISTER_USER: "REGISTER_USER",
    SIGNOUT: "SIGNOUT",
    JOIN_EVENT: "JOIN_EVENT",
    GET_DETAILED_EVENT: "GET_DETAILED_EVENT",
    LOGIN_USER: "LOGIN_USER",
};
