// eslint-disable-next-line import/prefer-default-export
export const ActionTypes = {
  FETCH_EVENTS: 'FETCH_EVENTS',
  POST_EVENT: 'POST_EVENT',
  REGISTER_USER: 'REGISTER_USER',
  GET_USER_INFO: 'GET_USER_INFO',
  SIGNOUT: 'SIGNOUT',
  JOIN_EVENT: 'JOIN_EVENT',
  GET_DETAILED_EVENT: 'GET_DETAILED_EVENT',
  LOGIN_USER: 'LOGIN_USER',
};
